
/* This Header file contains all the colors combinations. */

#define grey "\x1b[30m"
#define red "\x1b[31m"
#define green "\x1b[32m"
#define yellow "\x1b[33m"
#define blue "\x1b[34m"
#define voilet "\x1b[35m"
#define cyan "\x1b[36m"
#define bold "\x1b[1m"
#define italic "\x1b[3m"
#define underline "\x1b[4m"
#define crossline "\x1b[9m"
#define boxRed "\x1b[41m"
#define boxGreen "\x1b[42m"
#define boxYellow "\x1b[43m"
#define boxBlue "\x1b[44m"
#define boxVoilate "\x1b[45m"
#define boxcyan "\x1b[46m"
#define boxwhite "\x1b[47m"
#define colorReset "\x1b[0m"